version: '3.7'

services:
  peter-www:
    image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    container_name: peter-www
    environment:
      - TZ=Europe/Berlin
    networks:
      - traefik-public
    restart: unless-stopped
    labels:
      - traefik.frontend.rule=Host:www.peter.saarland
      - traefik.enable=true
      - traefik.port=80
      - traefik.protocol=http
      - traefik.docker.network=traefik-public
      - traefik.frontend.entryPoints=http,https
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.SSLHost=www.peter.saarland
      - traefik.frontend.headers.frameDeny=true
networks:
  traefik-public:
    external: true